name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
# type: Bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Please describe in detail what happened and what you expected to happen.
        Also include steps on how to reproduce the bug. 
        Feel free to add screenshots and any other relevant information that may also help us.

  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: "*Screenshots can be pasted from the clipboard directly into the issue description.*"
      placeholder: Describe the bug here...
      value: Oh no, there is a bug!
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: What version of OSIRIS are you using?
      placeholder: "e.g. v2.0.2, v2.1.0"
      value: "v2.0.2"
    validations:
      required: true

  - type: input
    id: browsers
    attributes:
      label: What Browser(s) are you seeing this bug on?
      placeholder: "e.g. Firefox, Chrome, Safari, Microsoft Edge"