
TYPES = {
    "journal-article": "article",
    "magazine-article": "magazine",
    "book-chapter": "chapter",
    "publication": "article",
    "doctoral-thesis": "dissertation",
    "master-thesis": "dissertation",
    "bachelor-thesis": "dissertation",
    "reviewer": "review",
    "editor": "editorial",
    "monograph": "book",
    "edited-book": "book",
    "posted-content": "preprint",
    "peer-review": "review",
    "report": "others",
    "working-paper": "others",
    "conference-paper": "others",
    "proceedings-article": "others",
    "conference-proceedings": "others",
    "conference-poster": "others",
    "conference-abstract": "others",
    "conference-review": "others",
    "conference-report": "others",
}